server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "health"

springdoc:
  swagger-ui:
    path=: "/jahia-contacts-api-swagger.html"
#"http://localhost:9090/jahia-contacts-api-swagger.html"